#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: c

env:
  global:
    # Use r-travis or r-builder? Currently only r-builder supports R-devel.
    - RENV="./pkg-build.sh"    # r-builder
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
    - _R_CHECK_FORCE_SUGGESTS_=false
    - BOOTSTRAP_PANDOC="true"

  # R versions r-builder should test on (ignored by r-travis)
  matrix:
    - RVERSION=devel

before_install:
  - echo RENV=$RENV
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/r-builder/master/pkg-build.sh;
  - chmod 755 $RENV
  - $RENV bootstrap

install:
  # Install bioc deps
  - $RENV install_bioc_deps
  # Need to specify VariantAnnotation and GenomicRanges because, although not
  # dependencies of methsim per se, they are dependencies of MethylationTuples
  # and these BioConductor package dependencies are not automatically installed
  # by devtools::install_github("PeteHaitch/MethylationTuples")
  - $RENV install_bioc GenomicTuples VariantAnnotation
  # Install GitHub deps
  - $RENV install_github PeteHaitch/MethylationTuples

script:
  - $RENV run_build
  - $RENV run_check

after_success:
  - $RENV dump_logs_by_extension out
  - $RENV install_github HenrikBengtsson/covr
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/covr-utils/master/covr-utils.R;
  - $RENV run_script .coveralls.R

after_failure:
  - $RENV dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
