// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// computeP
Rcpp::NumericMatrix computeP(NumericVector marginalProb, NumericVector LOR, int mc_order);
RcppExport SEXP methsim_computeP(SEXP marginalProbSEXP, SEXP LORSEXP, SEXP mc_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type marginalProb(marginalProbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LOR(LORSEXP);
    Rcpp::traits::input_parameter< int >::type mc_order(mc_orderSEXP);
    __result = Rcpp::wrap(computeP(marginalProb, LOR, mc_order));
    return __result;
END_RCPP
}
// simulateErrorInPlace
void simulateErrorInPlace(IntegerVector z, NumericVector u, double errorRate);
RcppExport SEXP methsim_simulateErrorInPlace(SEXP zSEXP, SEXP uSEXP, SEXP errorRateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type errorRate(errorRateSEXP);
    simulateErrorInPlace(z, u, errorRate);
    return R_NilValue;
END_RCPP
}
// simulatez
Rcpp::List simulatez(IntegerVector fh, IntegerVector nh, IntegerVector N, IntegerVector component, NumericMatrix MarginalProb, ListOf<NumericMatrix> P);
RcppExport SEXP methsim_simulatez(SEXP fhSEXP, SEXP nhSEXP, SEXP NSEXP, SEXP componentSEXP, SEXP MarginalProbSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type fh(fhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nh(nhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type component(componentSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type MarginalProb(MarginalProbSEXP);
    Rcpp::traits::input_parameter< ListOf<NumericMatrix> >::type P(PSEXP);
    __result = Rcpp::wrap(simulatez(fh, nh, N, component, MarginalProb, P));
    return __result;
END_RCPP
}
// tabulatez
std::map<std::string, std::vector<int> > tabulatez(IntegerVector readID, IntegerVector z, IntegerVector pos, int size);
RcppExport SEXP methsim_tabulatez(SEXP readIDSEXP, SEXP zSEXP, SEXP posSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type readID(readIDSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    __result = Rcpp::wrap(tabulatez(readID, z, pos, size));
    return __result;
END_RCPP
}
